var classes = [
    {
        "name": "App\\Availability",
        "interface": false,
        "methods": [
            {
                "name": "resources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Category",
        "interface": false,
        "methods": [
            {
                "name": "resources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.07,
        "afferentCoupling": 11,
        "efferentCoupling": 1,
        "instability": 0.08,
        "violations": {}
    },
    {
        "name": "App\\Console\\Commands\\Inspire",
        "interface": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Console\\Command",
            "Illuminate\\Foundation\\Inspiring"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0.5,
        "effort": 5,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 20,
        "number_operators": 2,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 15,
        "loc": 25,
        "lloc": 10,
        "mi": 117.65,
        "mIwoC": 71.05,
        "commentWeight": 46.6,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Console\\Kernel",
        "interface": false,
        "methods": [
            {
                "name": "schedule",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Console\\Kernel",
            "Illuminate\\Console\\Scheduling\\Schedule"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 13,
        "loc": 21,
        "lloc": 8,
        "mi": 217.94,
        "mIwoC": 171,
        "commentWeight": 46.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Events\\Event",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Exceptions\\Handler",
        "interface": false,
        "methods": [
            {
                "name": "report",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Exceptions\\Handler",
            "Exception",
            "parent",
            "Exception",
            "parent"
        ],
        "lcom": 2,
        "length": 7,
        "vocabulary": 3,
        "volume": 11.09,
        "difficulty": 1.5,
        "effort": 16.64,
        "level": 0.67,
        "bugs": 0,
        "time": 1,
        "intelligentContent": 7.4,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 20,
        "loc": 33,
        "lloc": 13,
        "mi": 114.96,
        "mIwoC": 68.25,
        "commentWeight": 46.71,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 2.25,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 4.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\AuthController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validator",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "registerUser",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "changePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Validator",
            "App\\User",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\DB",
            "App\\User",
            "App\\User",
            "Illuminate\\Http\\Request",
            "App\\Http\\Controllers\\Auth\\Auth"
        ],
        "lcom": 7,
        "length": 112,
        "vocabulary": 44,
        "volume": 611.46,
        "difficulty": 5.45,
        "effort": 3331.65,
        "level": 0.18,
        "bugs": 0.2,
        "time": 185,
        "intelligentContent": 112.22,
        "number_operators": 27,
        "number_operands": 85,
        "number_operators_unique": 5,
        "number_operands_unique": 39,
        "cloc": 60,
        "loc": 124,
        "lloc": 64,
        "mi": 84.86,
        "mIwoC": 40.82,
        "commentWeight": 44.04,
        "kanDefect": 0.44,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 144.58,
        "totalStructuralComplexity": 1008,
        "totalDataComplexity": 4.08,
        "totalSystemComplexity": 1012.08,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\PasswordController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 15,
        "loc": 24,
        "lloc": 9,
        "mi": 123.98,
        "mIwoC": 76.94,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\CategoryController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "upload",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 9,
        "nbMethods": 9,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 9,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Category",
            "Illuminate\\Http\\Request",
            "App\\Category",
            "App\\Category",
            "Illuminate\\Http\\Request",
            "App\\Category",
            "App\\Category",
            "Illuminate\\Http\\Request"
        ],
        "lcom": 9,
        "length": 74,
        "vocabulary": 18,
        "volume": 308.57,
        "difficulty": 7.57,
        "effort": 2336.35,
        "level": 0.13,
        "bugs": 0.1,
        "time": 130,
        "intelligentContent": 40.76,
        "number_operators": 21,
        "number_operands": 53,
        "number_operators_unique": 4,
        "number_operands_unique": 14,
        "cloc": 44,
        "loc": 98,
        "lloc": 54,
        "mi": 87.72,
        "mIwoC": 44.64,
        "commentWeight": 43.07,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.97,
        "relativeSystemComplexity": 49.97,
        "totalStructuralComplexity": 441,
        "totalDataComplexity": 8.75,
        "totalSystemComplexity": 449.75,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Routing\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.14,
        "afferentCoupling": 7,
        "efferentCoupling": 1,
        "instability": 0.13,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\HomeController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\DB",
            "Illuminate\\Support\\Facades\\DB"
        ],
        "lcom": 2,
        "length": 31,
        "vocabulary": 23,
        "volume": 140.23,
        "difficulty": 1.33,
        "effort": 186.97,
        "level": 0.75,
        "bugs": 0.05,
        "time": 10,
        "intelligentContent": 105.17,
        "number_operators": 3,
        "number_operands": 28,
        "number_operators_unique": 2,
        "number_operands_unique": 21,
        "cloc": 31,
        "loc": 46,
        "lloc": 15,
        "mi": 106.96,
        "mIwoC": 59.18,
        "commentWeight": 47.78,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.17,
        "relativeSystemComplexity": 64.17,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.33,
        "totalSystemComplexity": 128.33,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ReportsController",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ReservationController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "categories",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "category",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reservations",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "calendar",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reservation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resource",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Reservations",
            "Illuminate\\Http\\Request",
            "Illuminate\\Support\\Facades\\Auth",
            "App\\Reservations",
            "Illuminate\\Http\\Request",
            "App\\Category",
            "App\\Resources",
            "App\\Resources",
            "App\\Reservations",
            "App\\Resources"
        ],
        "lcom": 15,
        "length": 100,
        "vocabulary": 29,
        "volume": 485.8,
        "difficulty": 2.89,
        "effort": 1403.42,
        "level": 0.35,
        "bugs": 0.16,
        "time": 78,
        "intelligentContent": 168.16,
        "number_operators": 22,
        "number_operands": 78,
        "number_operators_unique": 2,
        "number_operands_unique": 27,
        "cloc": 51,
        "loc": 128,
        "lloc": 77,
        "mi": 81.37,
        "mIwoC": 39.9,
        "commentWeight": 41.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 1.08,
        "relativeSystemComplexity": 65.08,
        "totalStructuralComplexity": 960,
        "totalDataComplexity": 16.22,
        "totalSystemComplexity": 976.22,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ResourceController",
        "interface": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "edit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Resources",
            "App\\Category",
            "Illuminate\\Http\\Request",
            "App\\Category",
            "App\\Resources",
            "App\\Category",
            "App\\Resources",
            "Illuminate\\Http\\Request",
            "App\\Resources"
        ],
        "lcom": 8,
        "length": 70,
        "vocabulary": 15,
        "volume": 273.48,
        "difficulty": 4.08,
        "effort": 1114.97,
        "level": 0.25,
        "bugs": 0.09,
        "time": 62,
        "intelligentContent": 67.08,
        "number_operators": 17,
        "number_operands": 53,
        "number_operators_unique": 2,
        "number_operands_unique": 13,
        "cloc": 44,
        "loc": 93,
        "lloc": 49,
        "mi": 89.69,
        "mIwoC": 45.93,
        "commentWeight": 43.75,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.64,
        "relativeSystemComplexity": 64.64,
        "totalStructuralComplexity": 512,
        "totalDataComplexity": 5.11,
        "totalSystemComplexity": 517.11,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Kernel",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "lcom": 0,
        "length": 9,
        "vocabulary": 9,
        "volume": 28.53,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 19,
        "loc": 26,
        "lloc": 7,
        "mi": 119.73,
        "mIwoC": 71.24,
        "commentWeight": 48.49,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\Authenticate",
        "interface": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "lcom": 1,
        "length": 17,
        "vocabulary": 9,
        "volume": 53.89,
        "difficulty": 2.75,
        "effort": 148.19,
        "level": 0.36,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 19.6,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 3,
        "number_operands_unique": 6,
        "cloc": 8,
        "loc": 23,
        "lloc": 15,
        "mi": 101.4,
        "mIwoC": 61.82,
        "commentWeight": 39.59,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.2,
        "relativeSystemComplexity": 17.2,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 17.2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\EncryptCookies",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RedirectIfAuthenticated",
        "interface": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 1.75,
        "effort": 45.24,
        "level": 0.57,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 14.77,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 8,
        "loc": 19,
        "lloc": 11,
        "mi": 109.34,
        "mIwoC": 67.12,
        "commentWeight": 42.21,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 5.67,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RoleMiddleware",
        "interface": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 4,
        "externals": [
            "Closure",
            "Auth"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 2.79,
        "effort": 185.08,
        "level": 0.36,
        "bugs": 0.02,
        "time": 10,
        "intelligentContent": 23.85,
        "number_operators": 7,
        "number_operands": 13,
        "number_operators_unique": 3,
        "number_operands_unique": 7,
        "cloc": 7,
        "loc": 25,
        "lloc": 18,
        "mi": 95.87,
        "mIwoC": 59.32,
        "commentWeight": 36.55,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.86,
        "relativeSystemComplexity": 36.86,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0.86,
        "totalSystemComplexity": 36.86,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\VerifyCsrfToken",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\Request",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Jobs\\Job",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 15,
        "lloc": 5,
        "mi": 218.68,
        "mIwoC": 171,
        "commentWeight": 47.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "lcom": 2,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 22,
        "lloc": 12,
        "mi": 214.23,
        "mIwoC": 171,
        "commentWeight": 43.23,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AuthServiceProvider",
        "interface": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider",
            "Illuminate\\Contracts\\Auth\\Access\\Gate"
        ],
        "lcom": 1,
        "length": 5,
        "vocabulary": 4,
        "volume": 10,
        "difficulty": 0,
        "effort": 0,
        "level": 1.6,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 4,
        "cloc": 11,
        "loc": 21,
        "lloc": 10,
        "mi": 116.08,
        "mIwoC": 71.05,
        "commentWeight": 45.03,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\EventServiceProvider",
        "interface": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider",
            "Illuminate\\Contracts\\Events\\Dispatcher",
            "parent"
        ],
        "lcom": 1,
        "length": 4,
        "vocabulary": 3,
        "volume": 6.34,
        "difficulty": 0,
        "effort": 0,
        "level": 1.5,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 11,
        "loc": 21,
        "lloc": 10,
        "mi": 117.47,
        "mIwoC": 72.44,
        "commentWeight": 45.03,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\RouteServiceProvider",
        "interface": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "map",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapWebRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider",
            "Illuminate\\Routing\\Router",
            "parent",
            "Illuminate\\Routing\\Router",
            "Illuminate\\Routing\\Router"
        ],
        "lcom": 2,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 14,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 27,
        "loc": 48,
        "lloc": 21,
        "mi": 105.74,
        "mIwoC": 59.86,
        "commentWeight": 45.88,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0.25,
        "relativeSystemComplexity": 9.25,
        "totalStructuralComplexity": 27,
        "totalDataComplexity": 0.75,
        "totalSystemComplexity": 27.75,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Reservation",
        "interface": false,
        "methods": [
            {
                "name": "resources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Reservations",
        "interface": false,
        "methods": [
            {
                "name": "resources",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0.5,
        "effort": 2.38,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 1,
        "number_operands": 2,
        "number_operators_unique": 1,
        "number_operands_unique": 2,
        "cloc": 0,
        "loc": 8,
        "lloc": 8,
        "mi": 75.43,
        "mIwoC": 75.43,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 1,
        "instability": 0.17,
        "violations": {}
    },
    {
        "name": "App\\Resources",
        "interface": false,
        "methods": [
            {
                "name": "category",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "availability",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "reservation",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0.7,
        "effort": 18.09,
        "level": 1.43,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 36.93,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 17,
        "lloc": 17,
        "mi": 63.13,
        "mIwoC": 63.13,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 5,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 3,
        "totalSystemComplexity": 15,
        "pageRank": 0.06,
        "afferentCoupling": 9,
        "efferentCoupling": 1,
        "instability": 0.1,
        "violations": {}
    },
    {
        "name": "App\\Staff",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.04,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\Student",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 4,
        "lloc": 4,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "App\\User",
        "interface": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "lcom": 0,
        "length": 8,
        "vocabulary": 7,
        "volume": 22.46,
        "difficulty": 0,
        "effort": 0,
        "level": 1.75,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 10,
        "loc": 17,
        "lloc": 7,
        "mi": 118.35,
        "mIwoC": 71.97,
        "commentWeight": 46.38,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "pageRank": 0.05,
        "afferentCoupling": 9,
        "efferentCoupling": 1,
        "instability": 0.1,
        "violations": {}
    },
    {
        "name": "CreateUsersTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 17,
        "vocabulary": 8,
        "volume": 51,
        "difficulty": 0,
        "effort": 0,
        "level": 0.94,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 48,
        "number_operators": 0,
        "number_operands": 17,
        "number_operators_unique": 0,
        "number_operands_unique": 8,
        "cloc": 10,
        "loc": 31,
        "lloc": 21,
        "mi": 97.6,
        "mIwoC": 59.07,
        "commentWeight": 38.53,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 128,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreatePasswordResetsTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0,
        "effort": 0,
        "level": 1.11,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 105.34,
        "mIwoC": 64.36,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 32,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateCategoriesTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 5,
        "volume": 23.22,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 10,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 27,
        "lloc": 17,
        "mi": 103.92,
        "mIwoC": 63.46,
        "commentWeight": 40.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 32,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateResourcesTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 19,
        "vocabulary": 9,
        "volume": 60.23,
        "difficulty": 0,
        "effort": 0,
        "level": 0.95,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 19,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 10,
        "loc": 30,
        "lloc": 20,
        "mi": 98.02,
        "mIwoC": 59.02,
        "commentWeight": 38.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 100,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 200,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateAvailabilitiesTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 16,
        "vocabulary": 7,
        "volume": 44.92,
        "difficulty": 0,
        "effort": 0,
        "level": 0.88,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 39.3,
        "number_operators": 0,
        "number_operands": 16,
        "number_operators_unique": 0,
        "number_operands_unique": 7,
        "cloc": 10,
        "loc": 29,
        "lloc": 19,
        "mi": 99.87,
        "mIwoC": 60.4,
        "commentWeight": 39.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 81,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 162,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateReservationsTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 30,
        "vocabulary": 14,
        "volume": 114.22,
        "difficulty": 0,
        "effort": 0,
        "level": 0.93,
        "bugs": 0.04,
        "time": 0,
        "intelligentContent": 106.61,
        "number_operators": 0,
        "number_operands": 30,
        "number_operators_unique": 0,
        "number_operands_unique": 14,
        "cloc": 11,
        "loc": 37,
        "lloc": 26,
        "mi": 91.98,
        "mIwoC": 54.59,
        "commentWeight": 37.39,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 100,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 200,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AddIconToCategoriesTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 8,
        "vocabulary": 3,
        "volume": 12.68,
        "difficulty": 0,
        "effort": 0,
        "level": 0.75,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 106.86,
        "mIwoC": 65.87,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 18,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AddReservationsToReservationsTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 4,
        "vocabulary": 2,
        "volume": 4,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 4,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 110.36,
        "mIwoC": 69.38,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 2,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateStudentsTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.03,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 22,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 10,
        "loc": 33,
        "lloc": 23,
        "mi": 94.64,
        "mIwoC": 56.99,
        "commentWeight": 37.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 128,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateStaffTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 22,
        "vocabulary": 11,
        "volume": 76.11,
        "difficulty": 0,
        "effort": 0,
        "level": 1,
        "bugs": 0.03,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 22,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 10,
        "loc": 33,
        "lloc": 23,
        "mi": 94.64,
        "mIwoC": 56.99,
        "commentWeight": 37.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 64,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 128,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "AddColorToCategoriesTable",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 8,
        "vocabulary": 3,
        "volume": 12.68,
        "difficulty": 0,
        "effort": 0,
        "level": 0.75,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 106.86,
        "mIwoC": 65.87,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 9,
        "totalStructuralComplexity": 18,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 18,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreatePermissionTables",
        "interface": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema",
            "Schema"
        ],
        "lcom": 2,
        "length": 98,
        "vocabulary": 16,
        "volume": 392,
        "difficulty": 3.2,
        "effort": 1254.4,
        "level": 0.31,
        "bugs": 0.13,
        "time": 70,
        "intelligentContent": 122.5,
        "number_operators": 2,
        "number_operands": 96,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 10,
        "loc": 58,
        "lloc": 48,
        "mi": 75.02,
        "mIwoC": 45.03,
        "commentWeight": 29.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 144,
        "totalStructuralComplexity": 288,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 288,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CategoryTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "Schema",
            "App\\Category",
            "Schema",
            "App\\Category"
        ],
        "lcom": 1,
        "length": 31,
        "vocabulary": 20,
        "volume": 133.98,
        "difficulty": 2.29,
        "effort": 307.37,
        "level": 0.44,
        "bugs": 0.04,
        "time": 17,
        "intelligentContent": 58.4,
        "number_operators": 5,
        "number_operands": 26,
        "number_operators_unique": 3,
        "number_operands_unique": 17,
        "cloc": 5,
        "loc": 21,
        "lloc": 16,
        "mi": 92.87,
        "mIwoC": 58.57,
        "commentWeight": 34.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "DatabaseSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Seeder"
        ],
        "lcom": 1,
        "length": 6,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0.33,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 6,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 8,
        "loc": 21,
        "lloc": 13,
        "mi": 211.85,
        "mIwoC": 171,
        "commentWeight": 40.85,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "PermissionTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Schema",
            "Spatie\\Permission\\Models\\Permission",
            "Schema",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission",
            "Spatie\\Permission\\Models\\Permission"
        ],
        "lcom": 1,
        "length": 20,
        "vocabulary": 11,
        "volume": 69.19,
        "difficulty": 0,
        "effort": 0,
        "level": 1.1,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 20,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 5,
        "loc": 25,
        "lloc": 20,
        "mi": 90.54,
        "mIwoC": 58.6,
        "commentWeight": 31.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 14,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ReservationsTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "Schema",
            "App\\Reservations",
            "Schema",
            "App\\Reservations"
        ],
        "lcom": 1,
        "length": 42,
        "vocabulary": 23,
        "volume": 189.99,
        "difficulty": 2.78,
        "effort": 527.22,
        "level": 0.36,
        "bugs": 0.06,
        "time": 29,
        "intelligentContent": 68.46,
        "number_operators": 5,
        "number_operands": 37,
        "number_operators_unique": 3,
        "number_operands_unique": 20,
        "cloc": 16,
        "loc": 32,
        "lloc": 16,
        "mi": 101.97,
        "mIwoC": 57.51,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "ResourceTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "Schema",
            "App\\Resources",
            "Schema",
            "App\\Resources"
        ],
        "lcom": 1,
        "length": 30,
        "vocabulary": 18,
        "volume": 125.1,
        "difficulty": 2.5,
        "effort": 312.74,
        "level": 0.4,
        "bugs": 0.04,
        "time": 17,
        "intelligentContent": 50.04,
        "number_operators": 5,
        "number_operands": 25,
        "number_operators_unique": 3,
        "number_operands_unique": 15,
        "cloc": 5,
        "loc": 21,
        "lloc": 16,
        "mi": 93.08,
        "mIwoC": 58.78,
        "commentWeight": 34.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 25,
        "totalStructuralComplexity": 25,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 25,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RoleHasPermissionTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Schema",
            "DB",
            "Schema",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role"
        ],
        "lcom": 1,
        "length": 65,
        "vocabulary": 17,
        "volume": 265.69,
        "difficulty": 1.91,
        "effort": 506.46,
        "level": 0.52,
        "bugs": 0.09,
        "time": 28,
        "intelligentContent": 139.38,
        "number_operators": 4,
        "number_operands": 61,
        "number_operators_unique": 1,
        "number_operands_unique": 16,
        "cloc": 5,
        "loc": 43,
        "lloc": 38,
        "mi": 73.63,
        "mIwoC": 48.43,
        "commentWeight": 25.2,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "RoleTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Schema",
            "Spatie\\Permission\\Models\\Role",
            "Schema",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role",
            "Spatie\\Permission\\Models\\Role"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 5,
        "volume": 18.58,
        "difficulty": 0,
        "effort": 0,
        "level": 1.25,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 5,
        "loc": 19,
        "lloc": 14,
        "mi": 101.66,
        "mIwoC": 65.98,
        "commentWeight": 35.68,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 4,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 4,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 8,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "StaffTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 3,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "App\\Staff",
            "App\\Staff"
        ],
        "lcom": 1,
        "length": 119,
        "vocabulary": 29,
        "volume": 578.1,
        "difficulty": 8.72,
        "effort": 5041.03,
        "level": 0.11,
        "bugs": 0.19,
        "time": 280,
        "intelligentContent": 66.3,
        "number_operators": 10,
        "number_operands": 109,
        "number_operators_unique": 4,
        "number_operands_unique": 25,
        "cloc": 5,
        "loc": 22,
        "lloc": 17,
        "mi": 87.08,
        "mIwoC": 53.42,
        "commentWeight": 33.66,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "StudentTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "Schema",
            "App\\Student",
            "Schema",
            "App\\Student"
        ],
        "lcom": 1,
        "length": 71,
        "vocabulary": 28,
        "volume": 341.32,
        "difficulty": 5.25,
        "effort": 1791.94,
        "level": 0.19,
        "bugs": 0.11,
        "time": 100,
        "intelligentContent": 65.01,
        "number_operators": 8,
        "number_operands": 63,
        "number_operators_unique": 4,
        "number_operands_unique": 24,
        "cloc": 5,
        "loc": 21,
        "lloc": 16,
        "mi": 90.03,
        "mIwoC": 55.73,
        "commentWeight": 34.3,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 36,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 36,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "UserTableSeeder",
        "interface": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "ccn": 2,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "Faker\\Factory",
            "Schema",
            "App\\User",
            "DB",
            "Schema",
            "App\\User",
            "App\\User",
            "App\\User",
            "App\\User",
            "App\\User"
        ],
        "lcom": 1,
        "length": 121,
        "vocabulary": 32,
        "volume": 605,
        "difficulty": 5.59,
        "effort": 3379.66,
        "level": 0.18,
        "bugs": 0.2,
        "time": 188,
        "intelligentContent": 108.3,
        "number_operators": 13,
        "number_operands": 108,
        "number_operators_unique": 3,
        "number_operands_unique": 29,
        "cloc": 5,
        "loc": 34,
        "lloc": 29,
        "mi": 76.34,
        "mIwoC": 48.35,
        "commentWeight": 27.99,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 49,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 49,
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 11,
        "instability": 1,
        "violations": {}
    }
]